"""Add goal to UserInteractions

Revision ID: 0cccfceaff03
Revises: 4a8d472b0017
Create Date: 2025-01-18 14:58:19.551598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cccfceaff03'
down_revision = '4a8d472b0017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FCgoal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('CBgoal', sa.Boolean(), nullable=True))
        batch_op.drop_column('goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('CBgoal')
        batch_op.drop_column('FCgoal')

    # ### end Alembic commands ###
