"""Add query_type to UserInteractions

Revision ID: 4a8d472b0017
Revises: 011938e30395
Create Date: 2025-01-18 01:20:43.795544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8d472b0017'
down_revision = '011938e30395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_column('query_type')

    # ### end Alembic commands ###
